# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbf7fd8f991aa8dee6e898644be6128011cb2cb1eb5d6a4b991ad52a7d89faaa137b402b9a7d944163e02b98f7199a0704e63861983f244ac95415b64b586a6b

test:
  secret_key_base: f5a36248ec929c6633431563351a173754b070ddeb534f28b5a7d2012f757f370556b322b12949377fa823cc3c3e56326f1f125373e00bfa29448a4fcf85889b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
